# Generated by Django 6.1 on 2026-09-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_cartitems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitems",
            old_name="added_at",
            new_name="created_at",
        ),
    ]
